update

diff --git a/.github/workflows/api-test.yaml b/.github/workflows/api-test.yaml
--- a/.github/workflows/api-test.yaml
+++ b/.github/workflows/api-test.yaml
@@ -55,9 +55,21 @@ jobs:
       - name: Get latest report folder
         id: get_report
         run: |
-          latest=$(ls -1 allure-history | grep -E '^[0-9]+$' | sort -n | tail -1)
-          echo "LATEST=$latest" >> $GITHUB_ENV
+          echo "📂 Checking allure-history contents..."
+          ls -R allure-history || echo "⚠️ allure-history not found"
+    
+          # Tìm folder dạng số
+          latest=$(find allure-history -maxdepth 1 -type d -regex '.*/[0-9]\+' | sed 's#.*/##' | sort -n | tail -1)
+
+          if [ -z "$latest" ]; then
+          echo "⚠️ Không tìm thấy folder số, fallback vào 'history'"
+          latest="history"
+          fi
           echo "Latest report folder: $latest"
+          echo "LATEST=$latest" >> $GITHUB_ENV
+
+    echo "Latest report folder: $latest"
+    echo "LATEST=$latest" >> $GITHUB_ENV
 
       - name: Publish test report
         uses: peaceiris/actions-gh-pages@v3
