update

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -34,8 +34,8 @@ jobs:
         run: mvn clean install -DskipTests=true
 
       - name: Run API tests with Maven
-        run: mvn test
-        continue-on-error: true
+        run: |
+          mvn clean test || echo "TEST_FAILED=true" >> $GITHUB_ENV
 
       - name: Archive Allure report
         uses: actions/upload-artifact@v4
